services:

  #  mysql:
  #    image: 'mysql:8.0.41'
  #    environment:
  #      - 'MYSQL_DATABASE=sample'
  #      - 'MYSQL_PASSWORD=1234'
  #      - 'MYSQL_ROOT_PASSWORD=1234'
  #      - 'MYSQL_USER=sample'
  #    ports:
  #      - '33062:3306'
  #    volumes:
  #      - mysql_data_2:/var/lib/mysql

  postgres:
    image: 'postgres:16.4-alpine'
    command: postgres -c 'max_connections=200' # 기본 설정은 100 이나, 200까지 확장
    environment:
      - 'POSTGRES_DB=sample'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=sample'
    ports:
      - '54322:5432'
    volumes:
      - postgres_data_2:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - "63792:6379"
    volumes:
      - redis_data_2:/data

volumes:
  postgres_data_2:
  #  mysql_data_2:
  redis_data_2:
